name: inactivity_screen_detector
description: The inactivity detector reacts to inactivity on the screen
version: 0.0.1

repository: https://github.com/JhoanSe7/inactivity_screen_detector.git

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.devteam.inactivity_screen_detector
        pluginClass: InactivityScreenDetectorPlugin
      ios:
        pluginClass: InactivityScreenDetectorPlugin
